project:
  type: website
  output-dir: _site
  resources:
    - cases/*.html

website:
  title: "Pain Medicine Learning Modules"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Modules
        menu:
          - text: All Modules
            href: modules.qmd
          - text: Pain Fundamentals
            href: pain-fundamentals-introduction.qmd
          - text: Back Pain Basics
            href: back-pain-introduction.qmd
          - text: Lumbar Radicular Pain
            href: radicular-pain-introduction.qmd

      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false
    page-layout: full
    include-after-body:
      - assets/back-pain-nav.html
      - assets/pain-fundamentals-nav.html
      - assets/radicular-pain-nav.html
      - assets/pain-fundamentals-nav.html
      - assets/radicular-pain-nav.html
